### ISSUE TITLE
golf: `JsonMaskObjectNIVC`

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#25]
Currently the specific:
```
JsonMaskObjectNIVC(1024, 10, 10)
```
is: `non-linear constraints: 365224`.

We need to reduce this.  I'm sure we can simplify this circuit!

**Comment by Autoparallel** [comment]
@lonerapier wanna take a look?

**Comment by lonerapier** [comment]
Looking into this, and most of it is due to not-so efficient substring search algorithm.

Large r1cs file of `LockHeader` template and high constraint count of `JsonMaskObjectNIVC` template depends upon string search for header/key.

- `LockHeader` -> `FirstStringMatch`
- `JsonMaskObjectNIVC` -> `KeyMatchAtDepth`

**Comment by Autoparallel** [comment]
I'm going to tackle this a different way with #41

**Comment by Autoparallel** [comment]
Closing this as we don't need to do this directly anymore.
